### ISSUE TITLE
Cannot read property 'outputs' of undefined

### ISSUE THREAD

**Issue by christroutner** [simpleledger/SLPDB#41]
This issue is related to testing out a patch for Issue #40.

SLPDB exited with the following output:

```
SLPJS Validating: ed1edc9dca2b6573d85d9bfc944f26b7c9e8d256e8f39552c7dea8ec953ea287
SLPJS Result: true (ed1edc9dca2b6573d85d9bfc944f26b7c9e8d256e8f39552c7dea8ec953ea287)
[INFO] JSON RPC: getTxOut f8b42574344527dd817d90e373aea2043125e56df5a7d8ca51c87f5699f22a70 2 true
[Query] queryForTxoInputAsSlpSend(f8b42574344527dd817d90e373aea2043125e56df5a7d8ca51c87f5699f22a70,2)
STR =  [
  {
    "txid": "b53aa58e93fbc68bdcba65a2c24dd55e99ccf48454b9fbaa962bb937797ebc9f",
    "block": 597769,
    "timestamp": "2019-08-28 15:28:05",
    "tokenid": "0df768b5485c72645de069b68f66d02205c26f827c608ef5ffa976266d753d50",
    "slp1": "0000000005f5e100",
    "slp2": "00000000e90ddd80",
    "slp3": null,
    "slp4": null,
    "slp5": null,
    "slp6": null,
    "slp7": null,
    "slp8": null,
    "slp9": null,
    "slp10": null,
    "slp11": null,
    "slp12": null,
    "slp13": null,
    "slp14": null,
    "slp15": null,
    "slp16": null,
    "slp17": null,
    "slp18": null,
    "slp19": null,
    "bch0": 0,
    "bch1": 2150,
    "bch2": 546,
    "bch3": 3958938,
    "bch4": null,
    "bch5": null,
    "bch6": null,
    "bch7": null,
    "bch8": null,
    "bch9": null,
    "bch10": null,
    "bch11": null,
    "bch12": null,
    "bch13": null,
    "bch14": null,
    "bch15": null,
    "bch16": null,
    "bch17": null,
    "bch18": null,
    "bch19": null
  }
]

SLPJS Validating: b53aa58e93fbc68bdcba65a2c24dd55e99ccf48454b9fbaa962bb937797ebc9f
SLPJS Result: true (b53aa58e93fbc68bdcba65a2c24dd55e99ccf48454b9fbaa962bb937797ebc9f)
TypeError: Cannot read property 'outputs' of undefined
    at SlpTokenGraph.<anonymous> (/home/trout/work/slpdb/slpdb/SlpTokenGraph.js:383:32)
    at Generator.next (<anonymous>)
    at fulfilled (/home/trout/work/slpdb/slpdb/SlpTokenGraph.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

I was running this commit to the `master` branch:
083f4622231dd4bfd50097ab7053a6b1d3dffa29

**Comment by christroutner** [comment]
This appears to be resolved in this commit: https://github.com/simpleledger/SLPDB/commit/fe3f8df762e2fb66e62f9b72c1e2915d25eb1ef1
