### ISSUE TITLE
Can we recover from MongoDB query timeouts?

### ISSUE THREAD

**Issue by christroutner** [simpleledger/SLPDB#53]
Below are stack traces from the QA server I run to test releases of SLPDB. I intentially run SLPDB on the machine with 2GB of RAM to see how it will respond in a less-than-optimal environment. I apply the same environment to each release I test, to look for changes.

SLPDB appears to consistently crash due to timeouts when trying to talk to MongoDB. The error is being caught appropriately in query.js, but then get's re-thrown, which ultimately causes MongoDB to crash and the Docker container to restart.

Is there some way the error could be handled? Like maybe with [p-retry](https://www.npmjs.com/package/p-retry)?

These errors were first seen in build commit `7675d9293ad43a6b7d017cbae8b56db76cf30e9c`. I revered the machine back to a known-good commit (`42dc8b7cad3845629095ca72ae210af05e04227d`), but saw the same errors. These crashes do not appear to be due to anything new that has been added to SLPDB.

Here are the stack traces:
```

    "[Thu, 12 Dec 2019 03:41:46 GMT] Error: _dbQuery failed with query {\"v\":3,\"q\":{\"db\":[\"c\"],\"find\":{\"out.s3\":\"MINT\",\"out.b4\":\"npnWPXX/PNynTJdnduUm0q/1ZUFggKh7pCf9gjA437c=\",\"out.b1\":\"U0xQAA==\"},\"sort\":{\"blk.i\":-1},\"limit\":1},\"r\":{\"f\":\"[ .[] | { block: (if .blk? then .blk.i else null end)} ]\"}} has response {\"errors\":[\"MongoNetworkError: connection 25 to 172.17.0.1:12301 timed out\"]}\n    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:48:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",

    "[Thu, 12 Dec 2019 03:37:11 GMT] Error: _dbQuery failed with query {\"v\":3,\"q\":{\"db\":[\"c\"],\"find\":{\"out.s3\":\"MINT\",\"out.b4\":\"/QHYZHYbgHIdKJ9+fVD3VJz020FGZXRyVreDIEWJx04=\",\"out.b1\":\"U0xQAA==\"},\"sort\":{\"blk.i\":-1},\"limit\":1},\"r\":{\"f\":\"[ .[] | { block: (if .blk? then .blk.i else null end)} ]\"}} has response {\"errors\":[\"MongoNetworkError: connection 26 to 172.17.0.1:12301 timed out\"]}\n    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:48:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at processTimers (internal/timers.js:472:9)",

    "[Thu, 12 Dec 2019 03:37:11 GMT] Error: _dbQuery failed with query {\"v\":3,\"q\":{\"db\":[\"c\"],\"find\":{\"out.s3\":\"SEND\",\"out.b4\":\"SDIm1m4tbASaHGXwUjzWyMiVxqYTrW6k7QrM80AlrgU=\",\"out.b1\":\"U0xQAA==\"},\"sort\":{\"blk.i\":-1},\"limit\":1},\"r\":{\"f\":\"[ .[] | { block: (if .blk? then .blk.i else null end)} ]\"}} has response {\"errors\":[\"MongoNetworkError: connection 25 to 172.17.0.1:12301 timed out\"]}\n    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:48:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",

    "[Thu, 12 Dec 2019 03:30:23 GMT] Error: _dbQuery failed with query {\"v\":3,\"q\":{\"db\":[\"c\"],\"find\":{\"out.s3\":\"SEND\",\"out.b4\":\"vGHUkpc09vBJwoO/ya+j8ra+HuNuDgrEh/OfYkWetIE=\",\"out.b1\":\"U0xQAA==\"},\"sort\":{\"blk.i\":-1},\"limit\":1},\"r\":{\"f\":\"[ .[] | { block: (if .blk? then .blk.i else null end)} ]\"}} has response {\"errors\":[\"MongoNetworkError: connection 24 to 172.17.0.1:12301 timed out\"]}\n    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:48:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at processTimers (internal/timers.js:472:9)",

    "[Thu, 12 Dec 2019 03:25:11 GMT] Error: _dbQuery failed with query {\"v\":3,\"q\":{\"db\":[\"c\"],\"find\":{\"out.s3\":\"MINT\",\"out.b4\":\"a0bKzzca2B+7QjHX4/XmHnHQ9JYjldKCRveiJ1sVtCk=\",\"out.b1\":\"U0xQAA==\"},\"sort\":{\"blk.i\":-1},\"limit\":1},\"r\":{\"f\":\"[ .[] | { block: (if .blk? then .blk.i else null end)} ]\"}} has response {\"errors\":[\"MongoNetworkError: connection 24 to 172.17.0.1:12301 timed out\"]}\n    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:48:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at runNextTicks (internal/process/task_queues.js:62:3)\n    at processTimers (internal/timers.js:472:9)"
```

**Comment by jcramer** [comment]
Thanks for the info Chris I will investigate this issue and circle back.

**Comment by jcramer** [comment]
I'm going to close this as it's an issue related to 0.15.x.  If it pops up in 1.0.0 we can re-open.  So far it hasn't shown up.
