### ISSUE TITLE
slpdb exit due to memory and bug

### ISSUE THREAD

**Issue by jingniao** [simpleledger/SLPDB#57]
slpdb version is 
```shell
commit b362fd2a803ac42e72b538c0939f89003a24a394
Author: James Cramer <jcramer@simpleledger.io>
Date:   Sat Feb 15 11:00:15 2020 -0500

    clarify realtime options
```
my slpdb exit log
it may becase the memory leak and get tx(pre tx in same block? or bitcoin cash rpc return error?)vin error
```log
grep -B 10 "Shutting down SLPDB" -r slpdbnew.log*
slpdbnew.log-[INFO] JSON RPC: getBlockInfo/getBlockHash 622741
slpdbnew.log-[INFO] JSON RPC: getBlockInfo/getBlockHeader 0000000000000000017d4bf6850e8b1043ba507f8c4550ebb3035ea4f2ba3e6c true
slpdbnew.log-[INFO] Sending telemetry update to status.slpdb.io for unknown-91237...
slpdbnew.log-[INFO] Crawling block 622741 hash: 0000000000000000017d4bf6850e8b1043ba507f8c4550ebb3035ea4f2ba3e6c       slpdbnew.log-Error: Graph item cannot have inputs less than outputs (txid: bf5b67d8efa1ef145b4781236933bec2dcb51d9edf676da5798b2f776114001d, inputs: 0 | 0, outputs: 200191563 | 2).
slpdbnew.log-    at SlpTokenGraph.<anonymous> (/var/viabtc/SLPDBNEW/slptokengraph.js:508:27)
slpdbnew.log-    at Generator.next (<anonymous>)
slpdbnew.log-    at fulfilled (/var/viabtc/SLPDBNEW/slptokengraph.js:5:58)
slpdbnew.log-    at runMicrotasks (<anonymous>)
slpdbnew.log-    at processTicksAndRejections (internal/process/task_queues.js:93:5)
slpdbnew.log:[INFO] Shutting down SLPDB... Tue Feb 18 2020 07:12:44 GMT+0800 (China Standard Time)
--
slpdbnew.log.1-[DEBUG] graphItemsUpsert - inserted: 6bf8a1f48b2e776a3ed09b51b08f39ac9be84608b84750b6881c8f7f44bb72cd   slpdbnew.log.1-[DEBUG] graphItemsUpsert - inserted: 7ec6b90df4eba41b44a62ed39ece95f101483f1b6389b78d081e37cddceca3aa   slpdbnew.log.1-[DEBUG] graphItemsUpsert - inserted: 8b8107d2f669d19b4435508e407380e5bb323b6d9debd518555db6801c39c67b   slpdbnew.log.1-[INFO] Sending telemetry update to status.slpdb.io for unknown-91237...
slpdbnew.log.1-Error: _dbQuery failed with query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000000fc1dcbf5d3dc73a2fe76ce6658ec979f386ca742ba2e3d"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["Error: spawn ENOMEM"]}   slpdbnew.log.1-    at Function.<anonymous> (/var/viabtc/SLPDBNEW/query.js:50:31)
slpdbnew.log.1-    at Generator.next (<anonymous>)
slpdbnew.log.1-    at fulfilled (/var/viabtc/SLPDBNEW/query.js:5:58)
slpdbnew.log.1-    at runMicrotasks (<anonymous>)
slpdbnew.log.1-    at processTicksAndRejections (internal/process/task_queues.js:93:5)
slpdbnew.log.1:[INFO] Shutting down SLPDB... Tue Feb 18 2020 04:06:43 GMT+0800 (China Standard Time)
```

**Comment by jingniao** [comment]
I check my another slpdb
`Graph item cannot have inputs less than outputs` has many
```log
slpdb.log-Error: Graph item cannot have inputs less than outputs (txid: 3db95f5934434d883aad22357e92b53301fa8688bb226b06cfc0380196aa61e4, inputs: 0 | 0, outputs: 199732619 | 2).
slpdb.log-    at SlpTokenGraph.<anonymous> (/var/viabtc/SLPDB/slptokengraph.js:508:27)
slpdb.log-    at Generator.next (<anonymous>)
slpdb.log-    at fulfilled (/var/viabtc/SLPDB/slptokengraph.js:5:58)
slpdb.log-    at runMicrotasks (<anonymous>)
slpdb.log-    at processTicksAndRejections (internal/process/task_queues.js:93:5)
slpdb.log:[INFO] Shutting down SLPDB... Tue Feb 18 2020 07:54:08 GMT+0800 (China Standard Time)

slpdb.log-Error: Graph item cannot have inputs less than outputs (txid: 411986d8ad6d9708c9f729150813322d4caccfc9d67c278de9d2fd1c917bf3dc, inputs: 0 | 0, outputs: 199738692 | 2).
slpdb.log-    at SlpTokenGraph.<anonymous> (/var/viabtc/SLPDB/slptokengraph.js:508:27)
slpdb.log-    at Generator.next (<anonymous>)
slpdb.log-    at fulfilled (/var/viabtc/SLPDB/slptokengraph.js:5:58)
slpdb.log-    at runMicrotasks (<anonymous>)
slpdb.log-    at processTicksAndRejections (internal/process/task_queues.js:93:5)
slpdb.log:[INFO] Shutting down SLPDB... Tue Feb 18 2020 07:54:08 GMT+0800 (China Standard Time)

slpdb.log.1-Error: Graph item cannot have inputs less than outputs (txid: 2fc2f24b28f970a6385db8d016c8ffff458e2800f24ab3232872fa46b1ecaa7b, inputs: 0 | 0, outputs: 199821255 | 2).
slpdb.log.1-    at SlpTokenGraph.<anonymous> (/var/viabtc/SLPDB/slptokengraph.js:508:27)
slpdb.log.1-    at Generator.next (<anonymous>)
slpdb.log.1-    at fulfilled (/var/viabtc/SLPDB/slptokengraph.js:5:58)
slpdb.log.1-    at runMicrotasks (<anonymous>)
slpdb.log.1-    at processTicksAndRejections (internal/process/task_queues.js:93:5)
slpdb.log.1:[INFO] Shutting down SLPDB... Tue Feb 18 2020 07:49:13 GMT+0800 (China Standard Time)
```

**Comment by jcramer** [comment]
Hi, would you please share the settings you have in bitcoin.conf?

**Comment by jcramer** [comment]
Closing this as the newer versions should have this resolved, please reopen if this is still an issue.
