### ISSUE TITLE
slpdb stop sync becase tx 3c7048e40d81239accf6b682420154cc792df7621674d764acf585e1332deb48

### ISSUE THREAD

**Issue by jingniao** [simpleledger/SLPDB#67]
error log:
```
[ERROR] unhandledRejection Error: Graph item cannot have inputs less than outputs (txid: 3c7048e40d81239accf6b682420154cc792df7621674d764acf58
5e1332deb48, inputs: 0 | 0, outputs: 9992400000000 | 2).
    at SlpTokenGraph.<anonymous> (/var/viabtc/SLPDB/slptokengraph.js:476:27)
    at Generator.next (<anonymous>)
    at fulfilled (/var/viabtc/SLPDB/slptokengraph.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[INFO] Block checkpoint retrieved:  643464 000000000000000001e4f0cf837432589bbfb1b551758d7901473f54e19d01cd
[INFO] JSON RPC: getMempoolInfo
[INFO] Sending telemetry update to status.slpdb.io for unknown-96400...
Error: Graph item cannot have inputs less than outputs (txid: 3c7048e40d81239accf6b682420154cc792df7621674d764acf585e1332deb48, inputs: 0 | 0,
 outputs: 9992400000000 | 2).
    at SlpTokenGraph.<anonymous> (/var/viabtc/SLPDB/slptokengraph.js:476:27)
    at Generator.next (<anonymous>)
    at fulfilled (/var/viabtc/SLPDB/slptokengraph.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[INFO] Shutting down SLPDB... Sun Jul 12 2020 08:14:16 GMT+0800 (China Standard Time)
```

**Comment by jingniao** [comment]
I use last master `44a07cd24b8d2974e1a75c8b80fbd5eb75980e20`

**Comment by jcramer** [comment]
please try the latest, i've changed some of the throw statements to print a warning instead until I can investigate the issue further.
