### ISSUE TITLE
slpdb stop sync in block number 643464

### ISSUE THREAD

**Issue by eager7** [simpleledger/SLPDB#68]
when i start slpdb program, the program will stop with below log:

`SLPJS Result: true (3c7048e40d81239accf6b682420154cc792df7621674d764acf585e1332deb48)
[INFO] Unpruned txn count: 116 (token: c96d703453a3c66e03c395619f824b1d69d1ee2c1a858c898b409483c94041cb)
[ERROR] unhandledRejection Error: Cannot have a SEND or MINT transaction without any input.
    at SlpTokenGraph.<anonymous> (/root/bitcoin_cash/SLPDB/slptokengraph.js:414:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/bitcoin_cash/SLPDB/slptokengraph.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[INFO] Block checkpoint retrieved:  643464 000000000000000001e4f0cf837432589bbfb1b551758d7901473f54e19d01cd
[INFO] JSON RPC: getMempoolInfo
[INFO] Sending telemetry update to status.slpdb.io for unknown-72059...
Error: Cannot have a SEND or MINT transaction without any input.
    at SlpTokenGraph.<anonymous> (/root/bitcoin_cash/SLPDB/slptokengraph.js:414:27)
    at Generator.next (<anonymous>)
    at fulfilled (/root/bitcoin_cash/SLPDB/slptokengraph.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[INFO] Shutting down SLPDB... Sun Jul 12 2020 08:50:01 GMT+0800 (GMT+08:00)`

i don't kown why,so i delete my slpdb dir and git clone new project, when i restart slpdb,the block number start with 543375...
so i need almost 10 hour to catch main net height.

help me,thanks

**Comment by jcramer** [comment]
please try the latest, i've changed some of the throw statements to print a warning instead until I can investigate the issue further.
