### ISSUE TITLE
Unrecognized field 'allowDiskUse'.

### ISSUE THREAD

**Issue by jcramer** [simpleledger/SLPDB#73]
Seeing some crashes with deployment using latest code:

```
Error: _dbQuery failed with query {"v":3,"q":{"db":"c","find":{"blk.h":"00000000000000000266f4cd5b35ea4a23a1c8ae94a73cba58c2dcff754ca5d8"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"00000000000000000266f4cd5b35ea4a23a1c8ae94a73cba58c2dcff754ca5d8\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"9b112819-7015-4506-a0c5-a1c83f921f13\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]} at Function.<anonymous> (/root/SLPDB/query.js:51:31) at Generator.next (<anonymous>) at fulfilled (/root/SLPDB/query.js:5:58) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jcramer** [comment]
fixed using Mongo 4.4+
