### ISSUE TITLE
SLPDB crashes after syncing with filter list

### ISSUE THREAD

**Issue by christroutner** [simpleledger/SLPDB#76]
SLPDB is using the `filters.yml` file to only sync a handful of tokens. It seems to sync fine, but then crashes after it completes its sync from genesis, then continues to crash anytime its started.

- I'm building on the latest SLPDB commit, `bb4a805610b9e4d67c1595b716df36190c75e8b1`
- I synced from the SLP genesis baked into SLPDB, so no change of DB corruption.
- Syncing against a BCHN full node: Bitcoin Cash Node:22.1.0(EB32.0)

Here is the output of SLPDB when I start it:

```
[ZMQ-SUB] New block found: 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361
[INFO] JSON RPC: getBlockInfo/getBlockHeader 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361 true
[INFO] Checking for reorg for 664507
[INFO] JSON RPC: getBlockHash 664507
[INFO] Confirmed actual block hash: 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361 at 664507
[INFO] SLPDB checkpoint is as least as long as the chain height.
[INFO] Stored hash: null at 664507
[INFO] Block checkpoint retrieved:  664506 000000000000000000eb7757a48caded0308b2d577bcdac3ff96f43c69679b4e
[INFO] JSON RPC: getBlockCount
[INFO] Prune stack at 664507, about to pop 0.
[INFO] JSON RPC: getBlockInfo/getBlockHash 664507
[INFO] JSON RPC: getBlockInfo/getBlockHeader 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361 true
[INFO] Crawling block 664507 hash: 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361
[DEBUG] Block 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361 has 8 txns
Toposort-664507: 0.700ms
[INFO] Block 664507 processed : 8 BCH tx | 0 SLP tx
[PERF] RPC END 664507: 10.835ms
[INFO] JSON RPC: getBlockHash 664507
burnSearch-664507: 0.125ms
[INFO] Block hash record deleted for 664407
[INFO] Block checkpoint updated to: 664507 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361
[PERF] DB Insert 664507: 1.943ms
[INFO] JSON RPC: getBlockCount
[INFO] Block checkpoint retrieved:  664507 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361
[INFO] JSON RPC: getRawMemPool
[INFO] Block checkpoint retrieved:  664507 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361
[Query] getTransactionsForBlock(000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361)
[ERROR] Retry 0, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 1, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 2, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 3, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 4, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] unhandledRejection Error: _dbQuery failed with query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:51:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[INFO] Block checkpoint retrieved:  664507 000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361
[INFO] JSON RPC: getMempoolInfo
[INFO] Sending telemetry update to status.slpdb.io for trout-devbox...
Error: _dbQuery failed with query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000001762d0fad915d5e43ee2af0001637bc575962726bb2e361\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"566fc7e1-eb1d-4d9b-80f5-e687bc3fc301\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:51:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[INFO] Shutting down SLPDB... Sat Dec 05 2020 00:49:56 GMT+0000 (Coordinated Universal Time)

```

**Comment by christroutner** [comment]
I watched the output for a while. The crash is happening every time a new block is found, and it finishes processing it.

Here is the output after it received block 664,511:

```
[ZMQ-SUB] New block found: 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190
[INFO] JSON RPC: getBlockInfo/getBlockHeader 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190 true
[INFO] Checking for reorg for 664511
[INFO] JSON RPC: getBlockHash 664511
[INFO] Confirmed actual block hash: 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190 at 664511
[INFO] SLPDB checkpoint is as least as long as the chain height.
[INFO] Stored hash: null at 664511
[INFO] Block checkpoint retrieved:  664510 000000000000000001b79cdf2a9ef4a7d5b0433af52029edebda3dab3dde79d7
[INFO] JSON RPC: getBlockCount
[INFO] Prune stack at 664511, about to pop 0.
[INFO] JSON RPC: getBlockInfo/getBlockHash 664511
[INFO] JSON RPC: getBlockInfo/getBlockHeader 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190 true
[INFO] Crawling block 664511 hash: 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190
[DEBUG] Block 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190 has 93 txns
[INFO] SLP txn filtered and ignored: 190edfbdf4b8c5a63170f97d49c2ce52141a1c65388d0be7b0a4778d42b4e010
[INFO] SLP txn filtered and ignored: 1ee7f0218f10a3d8340487dce4672ca7e25193dadd6927dc3aa8657fd0e91797
[INFO] SLP txn filtered and ignored: 225407479bd32647c1069ba37d38d861e9f205a7896675cea617d6870752021b
[INFO] SLP txn filtered and ignored: 289c7453282fa51909f9c73f6580820dc6c7919c6c90fd61bec9e44359d88905
[INFO] SLP txn filtered and ignored: 28be15be011badc1385fff0d9a7eb467b316bbbe3dd4a40479788d0d5b5255c3
[INFO] SLP txn filtered and ignored: 2e4d8ac624328f7ab01e07abd1b3ba78911501e5cbdace134e9a393bb50b8e62
[INFO] SLP txn filtered and ignored: 40d1674526222c70f6ea37f4ef7767fc71de079d2509960241026cdfd9224156
[INFO] SLP txn filtered and ignored: 4e068b6e370686a3646a0e5933911e5d09ab9e8a576c900e634a139c2bf81dc9
[INFO] SLP txn filtered and ignored: 5a5376bda7f026bcb65b370c0bf707fa4afe4240351595f230b3feb44b988300
[INFO] SLP txn filtered and ignored: 683ddc4581615629b7f65bfa9633d3c667e1d68c445ff13b7d27932bfe84be9f
[INFO] SLP txn filtered and ignored: 6b5077b1f10d695b01614de807224e15af8fda36d1394efa37515e363ae3f92f
[INFO] SLP txn filtered and ignored: 6c922d9c1ab0b759d97ae08ba779f2b8be19d3e3c044df4d1b0d173cd58c2ffe
[INFO] SLP txn filtered and ignored: 88c71826c52c076df5f52a80717d13361180e9633de0b1fd52747c64c498fdea
[INFO] SLP txn filtered and ignored: 9e733f2ff4426b320ef259c6766c8032329f4adf1b57df97b43c15ca2aa7d75f
[INFO] SLP txn filtered and ignored: c8ea93d2b6a59258914d634f5dde08247755d24fbb87e92f058c5b253f136a85
[INFO] SLP txn filtered and ignored: dc61389b665d0552d9c85b4e353c858f9c1f20cffc619f9b46d2ca99c51faa42
Toposort-664511: 22.019ms
[INFO] Block 664511 processed : 93 BCH tx | 0 SLP tx
[PERF] RPC END 664511: 57.483ms
[INFO] JSON RPC: getBlockHash 664511
burnSearch-664511: 0.779ms
[INFO] Block hash record deleted for 664411
[INFO] Block checkpoint updated to: 664511 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190
[PERF] DB Insert 664511: 3.988ms
[INFO] JSON RPC: getBlockCount
[INFO] Block checkpoint retrieved:  664511 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190
[INFO] JSON RPC: getRawMemPool
[INFO] Block checkpoint retrieved:  664511 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190
[Query] getTransactionsForBlock(000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190)
[ERROR] Retry 0, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 1, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[INFO] Transaction ignored: 80fb1bd24fd01fdc857baeafc32960dfff521b9b4cdd0ae0ad5a751b51e4438d
[ERROR] Retry 2, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 3, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] Retry 4, after mongo query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
[ERROR] unhandledRejection Error: _dbQuery failed with query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:51:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[INFO] Block checkpoint retrieved:  664511 000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190
[INFO] JSON RPC: getMempoolInfo
[INFO] Sending telemetry update to status.slpdb.io for trout-devbox...
Error: _dbQuery failed with query {"v":3,"q":{"db":"c","find":{"blk.h":"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190"},"limit":10000000},"r":{"f":"[ .[] | { txid: .tx.h, timestamp: (if .blk? then (.blk.t | strftime(\"%Y-%m-%d %H:%M:%S\")) else null end), slp: .slp } ]"}} has response {"errors":["MongoError: Failed to parse: { find: \"confirmed\", filter: { blk.h: \"000000000000000002d9bb1f42a7bbb913ee61d5dd3086142ac118d36a6ae190\" }, allowDiskUse: true, sort: { blk.i: -1 }, limit: 10000000, returnKey: false, showRecordId: false, lsid: { id: UUID(\"60d92a7e-bede-49aa-92f6-e83709baba41\") }, $db: \"slpdb\" }. Unrecognized field 'allowDiskUse'."]}
    at Function.<anonymous> (/home/safeuser/SLPDB/query.js:51:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/safeuser/SLPDB/query.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[INFO] Shutting down SLPDB... Sat Dec 05 2020 01:03:05 GMT+0000 (Coordinated Universal Time)

```

**Comment by jcramer** [comment]
The mongo error says unrecognized parameter "allowDiskUse".  I wonder if it shouldn't be there or if there's a mongo version issue.

**Comment by christroutner** [comment]
Ya. I just noticed that this  might be related to #73. I'm using the Docker container [mongo:4.2-bionic](https://hub.docker.com/_/mongo).

Is there a specific version of mongo that does not exhibit these issues?

**Comment by christroutner** [comment]
What's strange is that I don't get this issue unless I use the `filter.yml` file. That's the only thing that's changed in the code or environment.

**Comment by christroutner** [comment]
I upgraded to the `mongo:4.4.2-bionic` image and it stopped crashing.
