### ISSUE TITLE
Failing to start process

### ISSUE THREAD

**Issue by nyusternie** [simpleledger/SLPDB#79]
I was trying to update my SLPDB code, as I've been having sync issues lately and I see there is a new rc, but it's failing to start on any commit after this one:

```
commit a7bad2b8934af1e1406baf03294712379171f4f4
Author: James Cramer <jcramer@simpleledger.io>
Date:   Mon Sep 21 11:16:34 2020 -0400

    add mongo client option useUnifiedTopology
```

if I try to `npm start` using `5bd24bf14c523b36b60a9f181f5f6ad5b872dae1`, I get the following error below:

```
> slpdb@1.0.0-beta-rc12 start /usr/src/slpdb
> tsc && node --max_old_space_size=8192 index run

[INFO] JSON RPC: getBlockchainInfo
(node:16100) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
/usr/src/slpdb/node_modules/mongodb/lib/mongo_client.js:306
    throw new MongoError('MongoClient must be connected before calling MongoClient.prototype.db');
    ^

MongoError: MongoClient must be connected before calling MongoClient.prototype.db
    at MongoClient.db (/usr/src/slpdb/node_modules/mongodb/lib/mongo_client.js:306:11)
    at new Db (/usr/src/slpdb/db.js:20:30)
    at Object.<anonymous> (/usr/src/slpdb/index.js:34:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  [Symbol(mongoErrorContextSymbol)]: {}
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slpdb@1.0.0-beta-rc12 start: `tsc && node --max_old_space_size=8192 index run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slpdb@1.0.0-beta-rc12 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-11T00_35_21_868Z-debug.log
```

@jcramer Can you briefly explain what changed in `5bd24bf14c523b36b60a9f181f5f6ad5b872dae1` and what I should do to run the latest code?

Thanks!

**Comment by jcramer** [comment]
Closing this, if you're still having issues try the 1.0.0 release with Mongo 4.4+
